### ISSUE TITLE
CI: Testing LowResTimer failed on macOs occasionally

### ISSUE THREAD

**Issue by 4eUeP** [haskell-Z/z-io#3]
See: https://github.com/haskell-Z/z-io/runs/1303668403

**Comment by winterland1989** [comment]
I'm trying to fix this problem in af57979, but now OSX can't run through the testsuit. On my local MacBook there's no problem, can you confirm on yours?

**Comment by 4eUeP** [comment]
emmm...I don't have any osx devices... ( btw, on my linux desktop, there's also no problem.

**Comment by winterland1989** [comment]
Great job fixing all these ; )
